package v1

import (
	bc "application/blockchain"
	"application/model"
	"application/pkg/app"
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	uuid2 "github.com/google/uuid"
	"github.com/hyperledger/fabric-sdk-go/pkg/client/channel"
	"net/http"
	"time"
)

type ProposalRequestBody struct {
	ProposalID        string `json:"proposal_id" form:"proposal_id"`
	SubProposalString string `json:"sub_proposal" form:"sub_proposal"`
	UserID            string `json:"user_id" form:"user_id"`
}

func GetProposal(c *gin.Context) {
	appG := app.Gin{C: c}
	body := new(ProposalRequestBody)
	//解析Body参数
	err := c.ShouldBind(body)
	if err != nil {
		appG.Response(http.StatusBadRequest, "查询方案失败", fmt.Sprintf("参数出错%s", err.Error()))
		return
	}
	var bodyBytes [][]byte
	var resp channel.Response

	bodyBytes = append(bodyBytes, []byte(body.ProposalID))
	resp, err = bc.ChannelQuery("getProposal", bodyBytes)
	if err != nil {
		appG.Response(http.StatusInternalServerError, "按主键查询方案失败", err.Error())
		return
	}

	// todo: 反序列化json 可能存在问题
	var data map[string]interface{}
	if err = json.Unmarshal(resp.Payload, &data); err != nil {
		appG.Response(http.StatusInternalServerError, "查询方案失败", err.Error())
		return
	}
	appG.Response(http.StatusOK, "查询方案成功", data)
}

func GetProposalList(c *gin.Context) {
	appG := app.Gin{C: c}
	body := new(ProposalRequestBody)
	//解析Body参数
	err := c.ShouldBind(body)
	if err != nil {
		appG.Response(http.StatusBadRequest, "查询方案失败", fmt.Sprintf("参数出错%s", err.Error()))
		return
	}
	var bodyBytes [][]byte
	var resp channel.Response

	bodyBytes = append(bodyBytes, []byte(body.UserID))
	resp, err = bc.ChannelQuery("getProposalsByUserID", bodyBytes)
	if err != nil {
		appG.Response(http.StatusInternalServerError, "按用户ID查询方案失败", err.Error())
		return
	}

	// todo: 反序列化json 可能存在问题
	var data []map[string]interface{}
	if err = json.Unmarshal(resp.Payload, &data); err != nil {
		appG.Response(http.StatusInternalServerError, "查询方案失败", err.Error())
		return
	}
	appG.Response(http.StatusOK, "查询方案成功", data)
}

func CreateProposal(c *gin.Context) {
	appG := app.Gin{C: c}
	// 生成方案ID
	uuid := uuid2.New()
	proposalID := "p" + uuid.String()
	// 生成方案
	algSubList := []model.SubProposal{
		model.SubProposal{
			SubProposalID:       1,
			StorageUserId:       "200001100001",
			StorageUserName:     "仓储01",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330101",
			StartLocationName:   "S1",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "货车",
			TransportCount:      22,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 12.5 * 431,
			SubProposalCost:     3000 * 22,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       60,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       371,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       2,
			StorageUserId:       "200001100001",
			StorageUserName:     "仓储01",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330101",
			StartLocationName:   "S1",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "火车",
			TransportCount:      1,
			TransportTonnage:    800,
			TransportCapacity:   1200,
			SubProposalDuration: 20.3 * 23,
			SubProposalCost:     4500 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       3,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       20,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       3,
			StorageUserId:       "200001100001",
			StorageUserName:     "仓储01",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330101",
			StartLocationName:   "S1",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.6 * 28,
			SubProposalCost:     18000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       3,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       25,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       4,
			StorageUserId:       "200001100001",
			StorageUserName:     "仓储01",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330101",
			StartLocationName:   "S1",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "货车",
			TransportCount:      1,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 13 * 17,
			SubProposalCost:     3200 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       1,
				},
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构02",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       16,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       5,
			StorageUserId:       "200001100001",
			StorageUserName:     "仓储01",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330101",
			StartLocationName:   "S1",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "货机",
			TransportCount:      8,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.4 * 320,
			SubProposalCost:     16000 * 8,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       13,
				},
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       307,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       6,
			StorageUserId:       "200001100001",
			StorageUserName:     "仓储01",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330101",
			StartLocationName:   "S1",
			EndLocationCode:     "330107",
			EndLocationName:     "D3",
			TransportType:       "货车",
			TransportCount:      3,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 11.5 * 431,
			SubProposalCost:     2700 * 22,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       45,
				},
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       2,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       7,
			StorageUserId:       "200001100001",
			StorageUserName:     "仓储01",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330101",
			StartLocationName:   "S1",
			EndLocationCode:     "330107",
			EndLocationName:     "D3",
			TransportType:       "货机",
			TransportCount:      2,
			TransportTonnage:    20,
			TransportCapacity:   40,
			SubProposalDuration: 1.7 * 431,
			SubProposalCost:     19000 * 22,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       29,
				},
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       30,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       8,
			StorageUserId:       "200001100002",
			StorageUserName:     "仓储02",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330102",
			StartLocationName:   "S2",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "货车",
			TransportCount:      2,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 9.5 * 38,
			SubProposalCost:     2400 * 2,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       13,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       25,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       9,
			StorageUserId:       "200001100002",
			StorageUserName:     "仓储02",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330102",
			StartLocationName:   "S2",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "火车",
			TransportCount:      1,
			TransportTonnage:    800,
			TransportCapacity:   1200,
			SubProposalDuration: 13 * 492,
			SubProposalCost:     3000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       96,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       396,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       10,
			StorageUserId:       "200001100002",
			StorageUserName:     "仓储02",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330102",
			StartLocationName:   "S2",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.4 * 36,
			SubProposalCost:     16000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       31,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       5,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       11,
			StorageUserId:       "200001100002",
			StorageUserName:     "仓储02",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330102",
			StartLocationName:   "S2",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "货车",
			TransportCount:      2,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 9.8 * 31,
			SubProposalCost:     2500 * 2,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       31,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       12,
			StorageUserId:       "200001100002",
			StorageUserName:     "仓储02",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330102",
			StartLocationName:   "S2",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "火车",
			TransportCount:      1,
			TransportTonnage:    800,
			TransportCapacity:   1200,
			SubProposalDuration: 15.6 * 67,
			SubProposalCost:     3460 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       16,
				},
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       51,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       13,
			StorageUserId:       "200001100002",
			StorageUserName:     "仓储02",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330102",
			StartLocationName:   "S2",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.6 * 38,
			SubProposalCost:     18000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       38,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       14,
			StorageUserId:       "200001100002",
			StorageUserName:     "仓储02",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330102",
			StartLocationName:   "S2",
			EndLocationCode:     "330107",
			EndLocationName:     "D3",
			TransportType:       "货车",
			TransportCount:      1,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 11.3 * 19,
			SubProposalCost:     2650 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       19,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       15,
			StorageUserId:       "200001100003",
			StorageUserName:     "仓储03",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330103",
			StartLocationName:   "S3",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "货车",
			TransportCount:      9,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 10.4 * 169,
			SubProposalCost:     2600 * 9,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       73,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       96,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       16,
			StorageUserId:       "200001100003",
			StorageUserName:     "仓储03",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330103",
			StartLocationName:   "S3",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "火车",
			TransportCount:      1,
			TransportTonnage:    800,
			TransportCapacity:   1200,
			SubProposalDuration: 17.5 * 44,
			SubProposalCost:     3800 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       11,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       33,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       17,
			StorageUserId:       "200001100003",
			StorageUserName:     "仓储03",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330103",
			StartLocationName:   "S3",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.5 * 34,
			SubProposalCost:     17000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       1,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       33,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       18,
			StorageUserId:       "200001100003",
			StorageUserName:     "仓储03",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330103",
			StartLocationName:   "S3",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "货车",
			TransportCount:      2,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 12.5 * 31,
			SubProposalCost:     3100 * 2,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       3,
				},
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       28,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       19,
			StorageUserId:       "200001100003",
			StorageUserName:     "仓储03",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330103",
			StartLocationName:   "S3",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "火车",
			TransportCount:      1,
			TransportTonnage:    800,
			TransportCapacity:   1200,
			SubProposalDuration: 15.6 * 126,
			SubProposalCost:     3500 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       23,
				},
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       103,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       20,
			StorageUserId:       "200001100003",
			StorageUserName:     "仓储03",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330103",
			StartLocationName:   "S3",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.4 * 38,
			SubProposalCost:     16000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       17,
				},
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       21,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       21,
			StorageUserId:       "200001100003",
			StorageUserName:     "仓储03",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330103",
			StartLocationName:   "S3",
			EndLocationCode:     "330107",
			EndLocationName:     "D3",
			TransportType:       "货车",
			TransportCount:      6,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 11.5 * 105,
			SubProposalCost:     2700 * 6,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       9,
				},
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       96,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       22,
			StorageUserId:       "200001100003",
			StorageUserName:     "仓储03",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330103",
			StartLocationName:   "S3",
			EndLocationCode:     "330107",
			EndLocationName:     "D3",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.3 * 37,
			SubProposalCost:     15000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       2,
				},
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       35,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       23,
			StorageUserId:       "200001100004",
			StorageUserName:     "仓储04",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330104",
			StartLocationName:   "S4",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "货车",
			TransportCount:      1,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 14 * 19,
			SubProposalCost:     3400 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       12,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       7,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       24,
			StorageUserId:       "200001100004",
			StorageUserName:     "仓储04",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330104",
			StartLocationName:   "S4",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "火车",
			TransportCount:      1,
			TransportTonnage:    800,
			TransportCapacity:   1200,
			SubProposalDuration: 17.6 * 102,
			SubProposalCost:     3850 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       102,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       25,
			StorageUserId:       "200001100004",
			StorageUserName:     "仓储04",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330104",
			StartLocationName:   "S4",
			EndLocationCode:     "330105",
			EndLocationName:     "D1",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.7 * 30,
			SubProposalCost:     19000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       8,
				},
				model.DemandItem{
					DemandUserID:      "300001100001",
					DemandUserName:    "需求点01",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       22,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       26,
			StorageUserId:       "200001100004",
			StorageUserName:     "仓储04",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330104",
			StartLocationName:   "S4",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "货车",
			TransportCount:      2,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 12.4 * 39,
			SubProposalCost:     3000 * 2,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       6,
				},
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       33,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       27,
			StorageUserId:       "200001100004",
			StorageUserName:     "仓储04",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330104",
			StartLocationName:   "S4",
			EndLocationCode:     "330106",
			EndLocationName:     "D2",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.6 * 37,
			SubProposalCost:     18000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       13,
				},
				model.DemandItem{
					DemandUserID:      "300001100002",
					DemandUserName:    "需求点02",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       24,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       28,
			StorageUserId:       "200001100004",
			StorageUserName:     "仓储04",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330104",
			StartLocationName:   "S4",
			EndLocationCode:     "330107",
			EndLocationName:     "D3",
			TransportType:       "货车",
			TransportCount:      1,
			TransportTonnage:    15,
			TransportCapacity:   20,
			SubProposalDuration: 10.8 * 18,
			SubProposalCost:     2600 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       18,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
		model.SubProposal{
			SubProposalID:       29,
			StorageUserId:       "200001100004",
			StorageUserName:     "仓储04",
			StorageUserTel:      "133xxxx3333",
			StorageUserAddress:  "xx省xx市xx区xx街道xx",
			StorageOrgID:        "200001",
			StorageOrgName:      "供应机构01",
			IsStorageConfirm:    false,
			TransportOrgID:      "400001",
			TransportOrgName:    "物流企业01",
			IsTransportConfirm:  false,
			StartLocationCode:   "330104",
			StartLocationName:   "S4",
			EndLocationCode:     "330107",
			EndLocationName:     "D3",
			TransportType:       "货机",
			TransportCount:      1,
			TransportTonnage:    30,
			TransportCapacity:   40,
			SubProposalDuration: 1.8 * 27,
			SubProposalCost:     20000 * 1,
			DemandList: []model.DemandItem{
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6922266470912",
					GoodName:          "清风纸巾",
					GoodGrossWeight:   500.00,
					DemandCount:       6,
				},
				model.DemandItem{
					DemandUserID:      "300001100003",
					DemandUserName:    "需求点03",
					DemandUserTel:     "133xxxx3333",
					DemandUserAddress: "xx省xx市xx区xx街道xx",
					DemandOrgID:       "300001",
					DemandOrgName:     "需求机构01",
					IsDemandConfirm:   false,
					GoodCode:          "6920118553615",
					GoodName:          "金味麦片",
					GoodGrossWeight:   750.00,
					DemandCount:       21,
				},
			},
			AllDemandConfirm:     false,
			IsSubProposalConfirm: false,
		},
	}

	proposal := model.Proposal{
		Key:              proposalID,
		ObjectType:       "proposal",
		AdminUserID:      "100001000001",
		AdminUserName:    "系统管理员01",
		SubProposalList:  []model.SubProposal{},
		AlgSubList:       algSubList,
		AlgDuration:      39683.0,
		AlgCost:          433710,
		ProposalDuration: 39683.0,
		ProposalCost:     433710,
		CreateTime:       time.Now().Format("2006-01-02 15:04:05"),
	}
	proposalString, err := json.Marshal(proposal)
	if err != nil {
		appG.Response(http.StatusInternalServerError, "方案创建失败", err.Error())
		return
	}
	//调用智能合约
	var bodyBytes [][]byte
	bodyBytes = append(bodyBytes, []byte(proposalID))
	bodyBytes = append(bodyBytes, proposalString)
	_, err = bc.ChannelExecute("createProposal", bodyBytes)
	if err != nil {
		appG.Response(http.StatusInternalServerError, "方案创建失败", err.Error())
		return
	}
	data := map[string]string{
		"proposal_id": proposalID,
	}
	appG.Response(http.StatusOK, "成功", data)
}

func PostProposal(c *gin.Context) {
	appG := app.Gin{C: c}
	body := new(ProposalRequestBody)
	//解析Body参数
	err := c.ShouldBind(body)
	if err != nil {
		appG.Response(http.StatusBadRequest, "查询方案失败", fmt.Sprintf("参数出错%s", err.Error()))
		return
	}
	var subProposalList []model.SubProposal
	err = json.Unmarshal([]byte(body.SubProposalString), &subProposalList)
	if err != nil {
		appG.Response(http.StatusBadRequest, "查询方案失败", fmt.Sprintf("子方案解析错误%s", err.Error()))
		return
	}
	var bodyBytes [][]byte
	var resp channel.Response

	bodyBytes = append(bodyBytes, []byte(body.ProposalID))
	resp, err = bc.ChannelQuery("getProposal", bodyBytes)
	if err != nil {
		appG.Response(http.StatusInternalServerError, "查询方案失败", err.Error())
		return
	}
	proposal := model.Proposal{}
	if err = json.Unmarshal(resp.Payload, &proposal); err != nil {
		appG.Response(http.StatusInternalServerError, "方案反序列化失败", err.Error())
		return
	}
	proposal.SubProposalList = subProposalList
	proposalString, err := json.Marshal(proposal)
	if err != nil {
		appG.Response(http.StatusInternalServerError, "方案再序列化失败", err.Error())
		return
	}
	bodyBytes = append(bodyBytes, proposalString)
	_, err = bc.ChannelExecute("postProposal", bodyBytes)
	if err != nil {
		appG.Response(http.StatusInternalServerError, "方案发布失败", err.Error())
		return
	}
	appG.Response(http.StatusOK, "成功", nil)
}

func DeleteProposal(c *gin.Context) {
	appG := app.Gin{C: c}
	body := new(ProposalRequestBody)
	//解析Body参数
	err := c.ShouldBind(body)
	if err != nil {
		appG.Response(http.StatusBadRequest, "删除方案失败", fmt.Sprintf("参数出错%s", err.Error()))
		return
	}
	var bodyBytes [][]byte

	bodyBytes = append(bodyBytes, []byte(body.ProposalID))
	_, err = bc.ChannelExecute("deleteProposal", bodyBytes)
	if err != nil {
		appG.Response(http.StatusInternalServerError, "删除方案失败", err.Error())
		return
	}
	appG.Response(http.StatusOK, "成功", nil)
}
